name: 'Upload Artifacts'
description: 'Upload artifacts to MinIO storage'
inputs:
  path:
    description: 'Path to file or directory to be uploaded'
    required: true

  MINIO_ACCESS_KEY:
    description: 'Access key for the MinIO storage system'
    required: true

  MINIO_SECRET_KEY:
    description: 'Secret key for the MinIO storage system'
    required: true

  MINIO_URL:
    description: 'The MinIO storage system endpoint URL'
    required: true
    default: 'http://api.minio.uavlab.site/'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.MINIO_ACCESS_KEY }}
    - ${{ inputs.MINIO_SECRET_KEY }}
    - ${{ inputs.MINIO_URL }}
