name: 'Upload Artifacts'
description: 'Upload artifacts to MinIO storage'
inputs:
  path:
    description: 'Path to file or directory to be uploaded/downloaded'
    required: true

  src_path:
    description: 'Source path in MinIO (for download) or local path (for upload)'
    required: true

  tgt_path:
    description: 'Target path in MinIO (for upload) or local path (for download)'
    required: false
    default: './'

  bucket:
    description: 'MinIO bucket name'
    required: false
    default: 'artifacts'

  mode:
    description: 'Operation mode: upload or download'
    required: false
    default: 'upload'

  use_git:
    description: 'Use git repository info for path generation (true/false)'
    required: false
    default: 'true'

  minio_access_key:
    description: 'Access key for the MinIO storage system'
    required: true

  minio_secret_key:
    description: 'Secret key for the MinIO storage system'
    required: true

  minio_api_uri:
    description: 'The MinIO storage system API URL'
    required: true
    default: 'http://api.minio.uavlab.site/'

  uid:
    description: 'User ID to run the Docker container with (optional)'
    required: false
    default: '1001'

  gid:
    description: 'Group ID to run the Docker container with (optional)'
    required: false
    default: '1001'


runs:
  using: 'docker'
  image: 'Dockerfile'
