name: 'Upload Artifacts'
description: 'Upload artifacts to FTP server'
inputs:
  path:
    description: 'Filename to be uploaded'
    required: true

  MINIO_ACCESS_KEY:
    description: 'Access key for the minio storage system'
    required: true

  MINIO_SECRET_KEY:
    description: 'Secret key for the minio storage system'
    required: true
  MINIO_URL:
    description: 'The minio storage system should be available at this location'
    default: 'olegoshkaff.uavlab.loca'
runs:
  using: 'composite'
  steps:
    - name: Run bash script
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh && ${{ github.action_path }}/entrypoint.sh ${{ inputs.path }} ${{ inputs.MINIO_ACCESS_KEY }} ${{ inputs.MINIO_SECRET_KEY }} ${{ inputs.MINIO_URL }}
